### ISSUE TITLE
How should `sidebarAction` be considered, since it’s only implemented in two browsers?

### ISSUE THREAD

**Issue by ariasuni** [w3c/webextensions#21]
Both Firefox and Opera implements a mostly non-overlapping API under the [sidebarAction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction) namespace (agreeing on the [`sidebar_action`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) key of the `manifest.json`).

Considering that most browsers don’t implement it, should this be described somehow, and considered part of the main spec while being optional, or an extension of it? Is two implementors sufficient to be considered something we want to describe, for interoperability purposes? Anyway, I guess it could be good to have guidelines for vendor-specific extensions of the WebExtensions API so that the whole stays coherent (and fit for a potential later standardization).

**Comment by dotproto** [comment]
My first impression is that it probably makes sense for the specification effort to approach this as an optional module that individual vendors may choose to adopt. I think existing implementations may provide enough reference material to begin drafting a spec for this namespace, but we may not have enough input from implementers to include it a report (a formal document published by the group).

**Comment by therealglazou** [comment]
Let me just comment that a feature having two publicly shipped interoperable implementations will pass Candidate Recommendation's exit criteria and then qualifies for standardization...

**Comment by carlosjeurissen** [comment]
Naver Whale also implemented sidebar_action. Tho it's using a different syntax. For example, it requires the use of default_page instead of default_panel.

Even tho it tolerates the syntax of Opera and Firefox. Unlike those two browsers, it can't run alongside other action declarations (action, browser_action, page_action).

See: https://developers.whale.naver.com/api/extensions/sidebarAction/

**Comment by dotproto** [comment]
Agreed that we should not specify vendor-specific APIs in order to keep the main specification focused on cross-browser compatibility. Such capabilities may be added to the spec in the future if there's sufficient interest from other browsers.

**Comment by carlosjeurissen** [comment]
Unifying some form of sidebar api is tracked here:
https://github.com/w3c/webextensions/issues/128
