### ISSUE TITLE
Request: consider extension store implementation and review policy during specification process

### ISSUE THREAD

**Issue by twschiller** [w3c/webextensions#24]
**Context**

In practice, the extension manifest is a combination of 1) technical specification, 2) browser implementation quirks/bugs, 3) the technical limitations of the web store, and 4) the review policies of the web store

Examples:
3. The Firefox web store has a maximum file size of 4mb: https://github.com/mozilla/addons/issues/662
4. For Manifest V3: the Chrome Web Store has a review policy that "Specifically, all logic must be included in the extension's package", but allows for "remote configuration files": https://developer.chrome.com/docs/extensions/mv3/intro/mv3-overview/#remotely-hosted-code

**Request**

When standardizing the "manifest", also consider any relevant web store factors — i.e., the "API" of the web stores

Web stores can/should be able to have different review policies, but aligning on standard terminology (e.g., "logic") would help simplify debate

**Comment by tomayac** [comment]
+1, it would also massively help if stores agreed on required icon sizes and screenshot dimensions.

**Comment by dotproto** [comment]
Considering and discussing these factors seems uncontroversial, but I'm not sure it makes sense to bake them into the specification. 

For example, @tomayac highlighted icon size inconsistency across browsers and stores. To my knowledge browsers and stores have preferred sizes for display purposes, but none strictly require any given size. If preferred size icon is not provided, the browser will select the next closest appropriate size and scale the image. For a point of comparison, the [Web Application Manifest working draft](https://www.w3.org/TR/appmanifest/#icons-member) describes the icons property and algorithm used to load images from this object, but does not specify what sizes are permitted.

I think it may be best to discuss these factors and seek alignment across browsers and stores, but for that information to be documented in a separate [report](https://www.w3.org/community/about/faq/#how-do-we-publish-a-report). I think it's also within this group's purview to produce non-specification resources like test suites or tutorials.

**Comment by dotproto** [comment]
Agreed that this should be a consideration as we design APIs, but we don't have any specific action items or deliverables here.
