### ISSUE TITLE
Features exposed by both a browser's UI and the WebExtensions API should behave the same

### ISSUE THREAD

**Issue by ariasuni** [w3c/webextensions#26]
I would like the specification to recommend the implementors to make the features available both through the WebExtensions API and the browser interface to follow the same defaults.

Examples:

Calling `browser.tabs.create()` (without arguments) should do exactly the same as a user clicking on the general «New Tab» button/hitting the general «New Tab» of their browser.

Calling `browser.tabs.create({ url: "https://example.net/" })` (without defining the `index`) should do exactly the same as the user opening a link from another application.

Calling `browser.tabs.duplicate(tabId)` should duplicate the tab at the same place than it would if the user had called the browser duplicate feature on the tab with `tabId` through e.g. a contextual menu.

**Comment by dotproto** [comment]
Reworded the title because every time I read it I thought it meant that `window.open()` and `browser.tabs.create()` should behave the same.

**Comment by zombie** [comment]
I'm not sure tying API behaviors with user-facing behavior is a universal win.  Extensions might come to depend on a certain (current/default) behavior, but either the Firefox product team, or the user could change that in the future, at which point, changing the API behavior might disrupt extensions that assumed a specific thing.

**Comment by xeenon** [comment]
Safari pretty much does this today.

**Comment by patrickkettner** [comment]
Closing this after discussing in the WECG today. While we agree that we do not want to go out of our way to have differentiating behavior, there is situations where it may make sense.
