### ISSUE TITLE
Update contributing guide with info on current communication channels

### ISSUE THREAD

**Issue by dotproto** [w3c/webextensions#29]
Per [this discussion](https://github.com/w3c/webextensions/issues/13#issuecomment-864177738) in #13, we should expand the [contributing guide](https://github.com/w3c/webextensions/blob/main/CONTRIBUTING.md) to include more specific details on how we use our communication channels and our [meeting schedule](https://www.w3.org/community/webextensions/2021/06/18/wecg-public-meeting-schedule/).

> - Issues for specific topic and long-running conversations.
> - Conference calls to discuss topics that require higher bandwidth conversations than issues typically allow
> - Matrix for general chat, quick questions, pings, etc. We may ask participants to open issues here for tracking purposes.

**Comment by ariasuni** [comment]
I guess we should copy the links in the sidebar [the group’s page](https://www.w3.org/community/webextensions/), and add an explanation for each discussion channel.

**Comment by ariasuni** [comment]
Also I think it’s hard to find the Zoom link. Actually it’s on an «old» e-mail on the internal mailing list; and in each event description.

So I guess a link to [the calendar](https://www.w3.org/groups/cg/webextensions/calendar) is important too, as well as explaining that can find the link in the description of the event by logging in, or by importing the calendar with personal links (I missed that so I only had the meeting time and name, not the desc).
