### ISSUE TITLE
Link to join group doesn't work?

### ISSUE THREAD

**Issue by leggett** [w3c/webextensions#3]
When I follow [the link to join](https://www.w3.org/community/wecg/join), I get an error:
<img width="1218" alt="Screen Shot 2021-06-04 at 5 00 24 PM" src="https://user-images.githubusercontent.com/8763662/120873500-352e8580-c557-11eb-9c5c-91b10283636e.png">

But I could join from these links:

- https://www.w3.org/groups/cg/webextensions
- https://www.w3.org/community/webextensions/

**Comment by dotproto** [comment]
Where did you find the link to https://www.w3.org/community/wecg/join ? I saw a report of this on Twitter as well but I haven't been able to find the linking page in order to update it.

**Comment by leggett** [comment]
On https://github.com/w3c/webextensions/blob/main/CONTRIBUTING.md

**Comment by dotproto** [comment]
Fixed in this commit: https://github.com/w3c/webextensions/commit/78423ff9dc64f8a3706347ead207b8d24bbf661d
