### ISSUE TITLE
Adjust regular meeting schedule to accommodate the other side of the globe

### ISSUE THREAD

**Issue by dotproto** [w3c/webextensions#31]
Duringour [2021-06-24](https://github.com/w3c/webextensions/blob/main/_minutes/2021-06-24-wecg.md) meeting we briefly discussed the fact that our current meeting schedule takes place during the middle of the night for people living in in timezones between +7 UTC and -9 UTC.

In order to accommodate people in these timezones, the suggestion was put forward that we alternate between the current recurring meeting time (8 AM Pacific) and another time.

If possible, I would like the chairs and editors to be able to attend both meetings. Chairs are in PDT/PST while the editors are in CEST and IST. Given this, it looks like our best (only?) option may be [11 PM Pacific](https://www.worldtimebuddy.com/?qm=1&lid=8,100,12,30&h=8&sln=23-24).

**Comment by xeenon** [comment]
The 11pm pacific time works for me.

**Comment by mukul-p** [comment]
Works for me

**Comment by dotproto** [comment]
Thanks for the confirmation.

@kewisch, I believe @zombie is indisposed, do you know who we should work with on the Mozilla side to a) confirm whether this time works and b) make the appropriate adjustments to the scheduled Zoom meeting?

**Comment by kewisch** [comment]
I'm going to be out on PTO in this week, but @Rob--W may be able to help. The zoom meeting doesn't need any specific changes, the room can be used at any time. If there is a calendar invite I may not have access to that. Looking at schedules this would take it into the evening for Tomislav, but there at least isn't anything in his calendar. For me personally the time works.

**Comment by Rob--W** [comment]
8 AM PDT is 5 PM CEST,
11 PM PDT is 8 AM CEST.

Works for me.

Are we going to continue with 8 AM PDT this week, and alternate between the two time slots from then on? From the next meeting onwards, we should announce the time and date of the upcoming meeting at the end of the meeting (or earlier), and publish it in the minutes.

**Comment by dotproto** [comment]
> Are we going to continue with 8 AM PDT this week, and alternate between the two time slots from then on?

Sounds like a plan :)

> From the next meeting onwards, we should announce the time and date of the upcoming meeting at the end of the meeting (or earlier), and publish it in the minutes.

I think this is a great suggestion. @xeenon, any concerns with this plan?

**Comment by zombie** [comment]
Sorry for the delay folks, the plan sgtm.

**Comment by Jack-Works** [comment]
What's the final time? I hope there is a UTC version because converting from things like PDT is hard for me (I don't know if they're using daylight saving time).

**Comment by Rob--W** [comment]
The notes from the last meeting include a link to a website that converts to local time zones: https://www.worldtimebuddy.com/?qm=1&lid=8,100,12,30&h=8&date=2021-7-22&sln=23-24&hf=1

**Comment by Jack-Works** [comment]
> The notes from the last meeting include a link to a website that converts to local time zones: https://www.worldtimebuddy.com/?qm=1&lid=8,100,12,30&h=8&date=2021-7-22&sln=23-24&hf=1

It seems like this website doesn't support adding my own timezone, it only provides 4 fixed timezones.

**Comment by Rob--W** [comment]
> > The notes from the last meeting include a link to a website that converts to local time zones: https://www.worldtimebuddy.com/?qm=1&lid=8,100,12,30&h=8&date=2021-7-22&sln=23-24&hf=1
> 
> It seems like this website doesn't support adding my own timezone, it only provides 4 fixed timezones.

Go to the home page and add your location / time zone and PDT.

The link includes UTC, so if you know your time zone relative to UTC, then you can compute the time yourself.

Otherwise you can use your search engine to search for something like "11 pm PDT in CEST" (CEST is my time zone). At least DuckDuckGo and Google will show the result.

Thursday 11 PM PDT becomes (Friday) 8 AM CEST, in my case.

**Comment by Jack-Works** [comment]
So the next meeting is at 6 am on July 25 in UTC+0 and the next one is 3 pm on Aug 5 in UTC+0?

**Comment by Techdojo** [comment]
Do we want to have a registry or a document where members can check in
ahead of time to indicate their intention to attend or not?
Unfortunately I can't make the next meeting due to personal conflicts but
am happy to continue to attend at both time slots.

**Comment by Rob--W** [comment]
The meeting schedule has been posted at https://github.com/w3c/webextensions/blob/main/_minutes/README.md (via #42). This document lists the next two meetings. After each meeting, minutes (meeting notes) will be published along with another entry in the schedule.

**Comment by dotproto** [comment]
> Do we want to have a registry or a document where members can check in ahead of time to indicate their intention to attend or not?

I don't think we need something like this right now, but it may be useful in the future as we continue to evolve and we get a better sense of individuals' concerns. Does that sound reasonable?
