### ISSUE TITLE
Edge browser compatibility issue: `action.setTitle()`

### ISSUE THREAD

**Issue by hanguokai** [w3c/webextensions#32]
`browserAction.setTitle()` on Edge browser has a compatibility issue. It appends `, ${badge_text}` to title if the badge text is not empty. For example, if you set the badge text to "badge", and set title to "title", then the real title is "title, badge" on Edge browser.

It’s an unnecessary, smarty-pants behavior, and breaks compatibility. If developers want to set like that, they can set by themself. But Edge force to add badge text to title, developers have no way to remove them and can't show the same title on different browsers.

PS: If there is a issue on Chrome, I will report it to https://bugs.chromium.org/ . But I don't know where to report bug to Microsoft Edge.

**Comment by MaheshKumarJha** [comment]
@hanguokai Thank you for your feedback. The reason why this is done for Edge is to make the badge accessible to users via narrator or other voice assistants. 
The setTitle and getTitle still work with only the title - getTitle returns only the title part. Did you mean that tooltip shows "title, badge" in your comment above? Due to the accessibility part, whenever the badge is visible, it needs to be accessible since it is visually part of the action icon. So, its not an optional choice available to the developer as of now. Please let me know if you have any suggestions on how this can be changed to make it more developer friendly.

**Comment by hanguokai** [comment]
![setTitle](https://user-images.githubusercontent.com/776467/126125005-55d4ea57-1719-4353-a367-1fc2111a8155.png)

There is no problem with accessibility, the problem is that it should not be shown(see my screenshot above). Badge and Title are two different things, and two different UI parts. Now that the badge is displayed, why should it be repeatedly displayed on title? Users are very confused to see this extra thing if developer already set title.

I agree to provide accessibility. My suggestion: 
1. badge should not be shown in title, it should be a screen-reader-only(invisible) info. 
2. or badge and title are treat as two different things(not one thing) for accessibility.

**Comment by bcomnes** [comment]
Agree @hanguokai. Accessibility should not be an excuse to degrade the overall experience, or an excuse to not implement proper accessibility features that don't degrade user experience. Forcefully inserting the badge value in the title appears really hacky (on top of being totally unexpected e.g. where is this random ", 8" coming from, an accessibility issue in and of itself).

**Comment by xeenon** [comment]
I agree that extensions should be in 100% control of what appears in the tooltip (title). The badge text should be exposed separately and internally to the screen reader.

**Comment by dhjw** [comment]
This behavior is ridiculous and I will not publish my extension in Edge because of it.

**Comment by dhjw** [comment]
This behavior is ridiculous and I will not publish my extension for Edge because of it.

**Comment by dhjw** [comment]
This behavior is ridiculous and I will not publish my extension for Edge because of it. How's that for accessibility?

**Comment by carlosjeurissen** [comment]
@hanguokai Microsoft now provided us the right channels to report issues. See https://github.com/w3c/webextensions/issues/155 and https://github.com/w3c/webextensions/issues/155#issuecomment-1029956000

**Comment by dhjw** [comment]
I created a feedback [here](https://feedbackportal.microsoft.com/feedback/idea/24c872b5-a786-ec11-a81b-6045bd8295cb).

**Comment by carlosjeurissen** [comment]
As this seems to be an edge-only issue, I'm closing this issue in favor of:
https://github.com/microsoft/MicrosoftEdge-Extensions/issues/19

**Comment by hanguokai** [comment]
Thanks @dhjw and @carlosjeurissen for reporting this issue in other places.

**Comment by hanguokai** [comment]
This issue is now resolved in Edge browser. There is no redundant text in the title now.
