### ISSUE TITLE
Support for the distribution of Web apps?

### ISSUE THREAD

**Issue by hanguokai** [w3c/webextensions#38]
In the past, Chrome supports another type of extensions - Chrome apps, a special web apps distributed through Chrome Web Store. It was deprecated and will stop supporting. One reason for abandoning is that it uses a lot of proprietary APIs instead of web standard APIs. Its successor is PWA, standardized by [Web Applications Working Group](https://github.com/w3c/webappswg).

Although Chrome apps is deprecated, but Web apps are highly anticipated by developers. Currently, distributing web apps is a very fragmented experience:

- Let users install PWA from developer's website: Developers are required to use Service Worker for caching and upgrading web apps by themselves. And need to find a way to get users.
- [Publish PWA to the Microsoft Store](https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/microsoft-store)
- [Publish PWA to Google Play Store](https://chromeos.dev/en/publish/pwa-in-play) : but you know, play store is an android app store, not focus on Web.
- Encapsulating a Web app as a native app: like [Electron Apps](https://www.electronjs.org/), but this approach has some obvious drawbacks.

Web extensions can also be considered as a way to distribute Web apps. For example, packaging a web app as a web extension, when users click the extension icon, launch the web app. But this form seems to lack some of the features of a native app or PWA, and users don’t feel comfortable using it.

So I hope browser's extension store can better support web app, including functions and distribution.

**Comment by larsgk** [comment]
Hi @hanguokai - I agree that it would make sense to be able to bundle and install PWAs, have you seen  https://github.com/WICG/webpackage ?

**Comment by hanguokai** [comment]
I didn't pay attention to [webpackage](https://github.com/WICG/webpackage) before, but I can see that this is a positive attempt by web developers to distribute static web apps.

I am glad to see that browser vendors are willing to standardize the Web Extension together. The "extension store"(or call it "web store") is also suitable for distributing static web apps, so this is an opportunity for all browsers to support the distribution of web apps together.

Extension protocol "browser-extension://extension_id/my_app.html" is treated as secure contexts like http://localhost . It is suitable for independent offline applications, e.g. a pure web video player for local files. Another example, [Secure Shell App](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo) and [Secure Shell Extension](https://chrome.google.com/webstore/detail/secure-shell/iodihamcpbpeioajjeobimgagajmlibd), they are the same web app but two forms.

Distributing applications is an important thing for developers, and installation means distribution. There may be more than one form of distribution. I can't say which form is the best, but the web store is a natural form of distributing web apps, it is easier to be accepted by developers and users.

**Comment by dotproto** [comment]
> I am glad to see that browser vendors are willing to standardize the Web Extension together.

For clarity, that's not what this group is doing. Per [the announcement](https://www.w3.org/community/webextensions/2021/06/04/forming-the-wecg/), "this community group seeks to align on a common vision for browser extensions and to work towards future standardization." W3C community groups cannot create standards. 

> Community Groups may produce Reports; these are not standards-track documents but may become input to the standards process. For instance, a Community Group might gather to work on a new technical specification, or convene to have discussions about a tutorial for an existing specification.
> 
> source: [W3C Community & Business Groups FAQ](https://www.w3.org/community/about/faq/)

While the WECG is seeking to create a specification for WebExtensions, not everything related to browser extensions will be specified. Specifically, we are aiming to specify "a consistent model and common core of functionality, APIs, and permissions." With luck another body will be able to use the report we produce in whole or in part.

**Comment by hanguokai** [comment]
Thanks for pointing out the precise definition of W3C Community Group. At the same time, I'm sure it's appropriate to post this proposal here. Because it’s an idea at this stage. I think it’s a very important topic for the future.

**Comment by Rob--W** [comment]
Out of scope for this CG.
