### ISSUE TITLE
Considerations for alternative development environments / languages for Web extensions

### ISSUE THREAD

**Issue by Techdojo** [w3c/webextensions#41]
As mentioned in issue #39  - Web development is no longer just dominated by JavaScript.

Whilst Typescript is a valid and viable alternative and easy enough to work with for extension development. It would be useful to enable / document how to provide the necessary bindings so that application developers using languages that offer a javascript as a build target can create web extensions in their language of choice. For instance Dart, Go, Python, Ruby etc.

**Comment by Jack-Works** [comment]
They can create binding to the WebExtension API like any other Web API

**Comment by dotproto** [comment]
I agree with @Jack-Works's comment. I'm going to close this as a dupe of #39. @Techdojo, if you feel they are separate issue please share some additional information to help clarify the distinction.

**Comment by Techdojo** [comment]
@dotproto - happy to close this as dupe of #39
