### ISSUE TITLE
Participating in TPAC 2021 

### ISSUE THREAD

**Issue by dotproto** [w3c/webextensions#45]
This week the group's chairs received an email announcing that W3C has begun organizing TPAC 2021. Like last year, this will be a completely remote event. The following comes from the announcement email.

> TPAC 2021 will be virtual, and will be held from 18 to 29 October.
> \*The week from 25 to 29 October will be dedicated to the Joint and Group 
> meetings.*
> The format we propose focuses on collaborative meetings that bring together the community 
> and create momentum and brainstorming.

Full details on this event can be found at https://www.w3.org/wiki/TPAC/2021/GroupMeetings. Guidance on the role TPAC serves and recommendations for participation can be found at https://www.w3.org/Guide/meetings/tpac.html.

This is a good opportunity for us to publicise our CG and to begin collaborating with other with other groups relevant to our work. Let's use this issue to begin identifying the groups we want to reach out to, topics we want to discuss, conversations we'd like to organize, etc.

**Comment by xeenon** [comment]
Topics we should consider talking about at TPAC included Service Workers, Web App Manifest, Content Security Policy, Web Transport, and JavaScript for Isolated Worlds / Content Scripts (which would be TC39 and not W3C / TPAC.)

**Comment by xeenon** [comment]
WebDriver BD might be interested in Isolated Worlds and could be at TPAC too.

**Comment by dotproto** [comment]
As discussed in today's meeting, the [GroupMeetings](https://www.w3.org/wiki/TPAC/2021/GroupMeetings) page states, "Until 10 September please fill in the tables below with your preferred meeting dates and time. If flexible, please state a second option."

**Comment by dotproto** [comment]
About an hour ago I completed the process of sending emails to the chairs of the various working groups we're interested in meeting with during TPAC. I'll follow up here as we hear back.

**Comment by Rob--W** [comment]
TPAC 2021 is in the past, TPAC 2022 will be discussed at #232.
