### ISSUE TITLE
Firefox' webRequest.FilterResponse & more for all browsers. Against wastie of time & electricity

### ISSUE THREAD

**Issue by ImprovedTube** [w3c/webextensions#506]
- Browsers & Browser extensions should be able to regex-away/clean/block anything. Before processing/rendering starts. (Firefox: [webRequest.FilterResponse](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData))
     - A lot of effort is lost /locked in DOM-tinkering /reverse-engineering. Helps nobody.  ([example](https://greasyfork.org/en/scripts/473972-youtube-js-engine-tamer/code))
     - The HTML responses of top100 websites can be be large already, let alone the DOMs. The last paint can take several seconds on the average device at average usage. While the payload, that the users wanted can be < 1%,  while there could always remain a permanently cached UI. 

<img width="200" alt="youtube dom" src="https://user-images.githubusercontent.com/25022245/203651898-23e4545c-2a64-4059-8a05-c6af59d9fbc4.png"> <img width="300" alt="clean dom" src="https://user-images.githubusercontent.com/25022245/203651903-275ece4c-a717-4b9f-95f6-ddbf6df80641.png"> <img width="460" alt="lighthouse chrome" src="https://user-images.githubusercontent.com/25022245/203652834-5ad8e195-0f17-4c1a-928a-037129792e5a.png">
     

---
     
 (it can be done in chrome for debugging) <br> 
[![](https://github.com/w3c/webextensions/assets/25022245/3a6cb6cf-3c6d-4add-b569-06cd9bbf89d0)](https://github.com/google/tamperchrome)

**Comment by Rob--W** [comment]
Safari & Chrome are opposed. With that, there is no point in keeping this one open.
