### ISSUE TITLE
Is "WebExtensions" the correct name for this group & the spec it plans to develop?

### ISSUE THREAD

**Issue by dotproto** [w3c/webextensions#6]
A couple members of the [chromium-extensions](https://groups.google.com/a/chromium.org/g/chromium-extensions) group commented in a thread about the creation of the WECG with concerns around the use of the term "WebExtensions." Given that these concerns directly apply to this group, I have migrated the relevant discussion into this issue.

> Don't want to be too pedantic, but "WebExtensions" is a deprecated name for browser extensions, as far as I know. Unfortunately I couldn't find any source to support this statement.
> The word we should consider using is https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions.
> ilyaigpetrov - [Sat, 5 Jun 2021 21:15:58 -0700 (PDT)](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/V0C5o7xoTYs/m/NKV_ODTqAgAJ)

> I kind of agree with that. The term WebExtensions is misleading. It implies that what's being extended is the Web or Web technologies, when in fact is an extension to the browser's functionality.
> Or in more purist terms, it's just a Web application with additional privileges. Kind of like a Progressive Web App with privileges.
> hrg... @gmail.com - [Sun, 6 Jun 2021 12:27:01 -0700 (PDT)](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/V0C5o7xoTYs/m/-fr3busbAwAJ)

**Comment by Jack-Works** [comment]
What about UserAgentExtension

**Comment by ilyaigpetrov** [comment]
> What about UserAgentExtension

https://en.wikipedia.org/wiki/User_agent:
> In computing, a user agent is any software, acting on behalf of a user, which "retrieves, renders and facilitates end-user interaction with Web content."

I guess, RSS-reader is a user agent too.

**Comment by tophf** [comment]
The term was originally coined by Mozilla developers, AFAIK, as they were the first to implement this. The `Web` in the term tells us these extensions are based on open Web technologies e.g. every extension page including the background page is just a standard web page. Whereas old addons in Firefox were using custom protocols and such.

A more precise term would be **[OWP](https://www.w3.org/wiki/Open_Web_Platform)-based browser extensions**, I guess.

**Comment by hanguokai** [comment]
> A more precise term would be OWP-based browser extensions, I guess.

So I think "WebBrowserExtensions" is more intuitive. [Here](https://en.wikipedia.org/wiki/Web_browser) is the definition of Web browser.

Web standards focus on the functions inside web pages. In contrast, bookmarks manager, history manager, tabs or windows manager, customizing new tab page are not related to any functions in web pages, and also not related to server side functions.

**Comment by ShadowJonathan** [comment]
`BrowserExtensions` would imo then be less of a mouthful, but i digress.

**Comment by dotproto** [comment]
As I tried to dig around to find more on the history of the term "web extensions" (with or without the space), I came across some references in WebKit that seemed to predate Mozilla's use.

Out of curiosity, @xeenon, do you have any context on the use of WebExtensions in WebKit?

**Comment by yankovichv** [comment]
I will express my humble opinion. I have been developing extensions for several years. My experience of communicating with users, partners, and colleagues suggest that the best term is "Browser Extensions". This most accurately reflects the real essence of our work and our products. Even if we modify sites, we do so on behalf of the browser. And of course +1 to the comment of the respected @hanguokai — when it comes to changing a new tab, history, or downloads - these are all browser modifications.

But in any case, the name will not bring us success or failure. The main thing is what kind of work will be behind it.

**Comment by ThomasGreiner** [comment]
> I guess, RSS-reader is a user agent too.

With some adjustments, Firefox add-ons used to also work on Thunderbird. Plus, its MailExtensions _"are based on the WebExtension technology"_ ([source](https://developer.thunderbird.net/add-ons/mailextensions)). Then there's also Electron, which _"supports a subset of the Chrome Extensions API"_ ([source](https://www.electronjs.org/docs/api/extensions)).

On the other hand, not all APIs are relevant to all user agents (e.g. `browser.bookmarks`, `browser.topSites`).

Therefore web extensions could be understood as web technology-based software for extending the functionality of a web browser or any other user agent that is based on a web browser.

**Comment by mingyaulee** [comment]
I have some experience developing extensions and here's my opinion.

Please correct me if I'm wrong, this group is set up to define the specifications for
1. Manifest specification (permissions etc.)
2. JavaScript API specifications

The name for the JavaScript API is the one that has been named WebExtensions API by Firefox and as a whole (including manifest) is still called BrowserExtensions. [Source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) (The title of the page is Browser Extensions and the first paragraph mentions "WebExtensions API cross-browser technology”)

It does make sense to retain the name of WebExtensions for the API, reason being is that a browser's purpose is generally to serve the web, whereas a browser extension's purpose is to extend the web functionality using the APIs.

So I think that the name for this repository should probably be "BrowserExtensions" but the API specifications should be named "WebExtensions API".

**Comment by shwetank** [comment]
I personally would like to keep the term Web Extensions because it implies that these extensions use web technologies as an important part of it and are extending the web experience for users. 

I'm not too much in favour of the term 'browser extensions' because often times it gives the impression (to people not familiar with extensions development) that these are just using proprietary browser APIs and not really relying on web technology. The reality is that extensions rely as much on standard web technology as much as they do on specific browser APIs. With V3, its going to even more the case with event and background pages replaced with service workers etc. 

I've often seen feedback and concern from extension authors being dismissed in standards discussions simply because their use cases are not considered part of the web. So this often places extensions authors in the unenviable place of consuming web technology in order to exist, while still not having a say in having their feedback and use cases being considered in web standard discussions. 

Also, I would imagine we could take a common standard and have it apply to beyond standard browsers (e.g, for certain cases, we could have extensions for screen readers? - technically not a standard web browser, but still user-agents). @ThomasGreiner mentioned some other places beyond the browser where such APIs have worked in the past too.

**Comment by ilyaigpetrov** [comment]
> As I tried to dig around to find more on the history of the term "web extensions"[...]

I finally found the source that regards WebExtension term as deprecated:
https://wiki.mozilla.org/Add-ons/Terminology#:~:text=deprecated.

**Comment by mingyaulee** [comment]
> I finally found the source that regards WebExtension term as deprecated:
> https://wiki.mozilla.org/Add-ons/Terminology#:~:text=deprecated.

This is a good find. As mentioned in the page, WebExtensions represents the technology and it means the same thing as WebExtensions API. It's use is deprecated from representing an actual extension but it still represents the technology, so the term is not totally deprecated.

**Comment by xeenon** [comment]
> Out of curiosity, @xeenon, do you have any context on the use of WebExtensions in WebKit?

Those references likely go back to legacy Safari extensions which were also based on web technology.

**Comment by therealglazou** [comment]
The real question is, at least for me, what are the terms people are going to search on the Web looking for that technology. It seems to me that

1. "WebExtension" is currently the term used by many of my peers with less knowledge of the Standards' world. I use it all the time.
2. "cool URIs never change": https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
3. "Browser Extension" is also easy to understand, represents well what we want to achieve and is used by many

**Comment by zombie** [comment]
I mostly agree with Daniel.  While there was an early attempt from Mozilla and others to standardize on "Browser Extensions", it seems that the term WebExtensions has won mindshare across the industry.

Debating whether extensions are meant to extend the web or UA's interpretation of the web might be philosophical and not very productive.

Similarly, nitpicking the already established name seems a bit like bikeshedding, and in the interest of avoiding that, I propose we close this issue.

**Comment by ilyaigpetrov** [comment]
JavaScript's specification is called EcmaScript.
We may as well when talking to a user use "BrowserExtension" and when discussing related development APIs and standards we may use "WebExtensions".
Like it is explained by @mingyaulee.

**Comment by dotproto** [comment]
Closing this discussion [as suggested](https://github.com/w3c/webextensions/issues/6#issuecomment-859933878) by @zombie. As previously stated, we have a name and we should run with it unless/until it becomes a material issue. Until then we're largely just debating what color we should paint the shed (bikeshedding).
