### ISSUE TITLE
Add `name` and `short_name` descriptions

### ISSUE THREAD

**Issue by xeenon** [w3c/webextensions#60]
Add some prose for the `name` and `short_name` manifest keys.

**Comment by dotproto** [comment]
I was looking at the `name` property yesterday and noticed that [MDN notes](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/name) "Google Chrome and Microsoft Edge restrict the name length to 45 characters." It appears that both Chromium and Firefox allow actually allow arbitrary length strings, but CWS and AMO do not allow names longer than 45 characters. I did not test other stores or browsers.

In #24, @twschiller suggested that when specifying the manifest we should "also consider any relevant web store factors." Should we note in the specification that name length is limited to 45 characters?

**Comment by dotproto** [comment]
> Should we note in the specification that name length is limited to 45 characters?

I was originally inlined to say no, as browsers allow longer strings. As I've been considering this, though, it is a practical limit of the ecosystem and therefore something that extension authors need to be cognizant of. Going back to the [Priority of Constituencies](https://www.w3.org/TR/html-design-principles/#priority-of-constituencies), it seems like a requirement worth documenting.

**Comment by ariasuni** [comment]
MDN also advise to not go over 12 characters for [`short_name`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/short_name).

Maybe we could add a note, or a «The `name` value should be kept under 45 characters.»? At least I don’t think it needs in the current PR, we could think about it and add what we want later.
