### ISSUE TITLE
Adjust frequency of 11 PM PDT / 6 AM UTC meeting

### ISSUE THREAD

**Issue by Rob--W** [w3c/webextensions#63]
In https://github.com/w3c/webextensions/issues/31 we introduced a second time slot, to alternate between 8 AM PDT (3 PM UTC) and 11 PM PDT (6 AM UTC), to enable more people to join.

Although not everyone signs in, we do have some stats on the number of participants and two surveys with time preferences:
- 28 registered [attendees on 2021-06-24](https://github.com/w3c/webextensions/blob/main/_minutes/2021-06-24-wecg.md#attendees-sign-yourself-in) at 8 AM PDT (3 PM UTC).
- 1 out of 9 [attendees on 2021-07-22](https://github.com/w3c/webextensions/blob/main/_minutes/2021-07-22-wecg.md#attendees-sign-yourself-in) preferred the 11 PM PDT (6 AM UTC) time slot.
- 13 out of 25 [attendees on 2021-08-05](https://github.com/w3c/webextensions/blob/main/_minutes/2021-08-05-wecg.md#attendees-sign-yourself-in) preferred the 8 AM PDT (3 PM UTC) time slot.
- 12 registered [attendees on 2021-08-20](https://github.com/w3c/webextensions/blob/main/_minutes/2021-08-20-wecg.md#attendees-sign-yourself-in) at 11 PM PDT (6 AM UTC).

The 8 AM PDT (3 PM UTC) time slot is more popular than the 11 PM PDT (6 AM UTC) time slot, so it may make sense to increase the frequency of the former at the expense of the latter.

The schedule of the biweekly meeting is currently as follows, and alternates between the two:
- One meeting at 8 AM PDT (3 PM UTC)
- One meeting at 11 PM PDT (6 AM UTC) - i.e. every month

We could replace one 11 PM slot with a 8 AM slot:
- Three meetings at 8 AM PDT (3 PM UTC)
- One meeting at 11 PM PDT (6 AM UTC) - i.e. once every two months
 
If one out of four is too infrequent, then the following alternative may also work:
- Two meetings at 8 AM PDT (3 PM UTC)
- One meeting at 11 PM PDT (6 AM UTC) - i.e. once every 1½ month.

Please comment and share your preferences.

**Comment by wingman-jr-addon** [comment]
Both times are inconvenient for me: one overlaps with daily professional duties, and the other occurs at 1am local time, but I can make both/either work at least partially. Personally I would prefer a single time slot - even an awkward one - as I have noticed that more complex schedules often lead to people getting confused and accidentally missing meetings. However, I understand that that approach may be too limiting for the global participation needed here.

**Comment by xeenon** [comment]
I prefer the 8 AM PDT (3 PM UTC) time.

**Comment by Jack-Works** [comment]
I prefer 11 PM PDT (6 AM UTC)

**Comment by Rob--W** [comment]
During today's meeting we decided to use one time slot again (8 AM PDT / 3 PM UTC).

Feedback on the meeting times continues to be welcome on this issue.
