### ISSUE TITLE
Specify the hierarchy of files

### ISSUE THREAD

**Issue by ariasuni** [w3c/webextensions#64]
As far as I know, a WebExtensions is a hierarchy a files with:

- As its root, a `manifest.json`
- As its root also, an optional `_locales` directory
- All other files referenced by the manifest or the APIs (e.g. in `tabs.executeScript`) must be in the root or in a subdirectory.

A note could be added that since several browsers distribute extensions as zip, the limitation of this compression format should be taken into account (no need to add more details).

Sounds simple enough to describe, if I didn’t forget anything.

**Comment by xeenon** [comment]
We should avoid many specifics about the distribution format, since that is out of scope in the charter, but alluding to any limitations might be fine.

**Comment by carlosjeurissen** [comment]
A resource on the features and limitations per browser would still be very helpful for every developer. Yet this spec might not be the best place for that indeed.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dotproto** [comment]
TODO: assign @oliverdunk to this issue once we figure out why we can't ;)

**Comment by dotproto** [comment]
Another important (and possibly non-normative) note is that casing can lead to filename collisions in certain operating systems. This is occasionally a source of confusing bugs for extension developers. One practical (albeit boring) way to avoid these issues is to ensure that all paths and filenames are lowercase.

**Comment by dotproto** [comment]
I was about to note that Chrome requires that background service workers are located in the extension's root, but it looks like we resolved that issue: https://crbug.com/1136582

**Comment by Jack-Works** [comment]
And any files starts with `_` excludes `_locales` will be rejected by Chrome
