### ISSUE TITLE
Safari Extensions Permission Banner Not Documented

### ISSUE THREAD

**Issue by wydgetlabsadmin** [w3c/webextensions#741]
I’m trying to figure out how to trigger the "Additional Permissions Requested" banner, like what extensions like Honey and Coupert do, but I haven’t had any luck. I've attached an example of the banner to this email. We’ve got <all_urls> in the manifest, but because Safari exposes the ability to only give permission for the extension to run on certain domains, its possible for us to not ACTUALLY have the <all_urls> permission. In these situations, I’ve been trying things like dynamically requesting permissions and injecting scripts when tabs are created, activated, or navigated.

 For example: chrome.webNavigation.onCommitted.addListener(async ({ tabId, url }) => { try { await chrome.permissions.request({ permissions: ['scripting'], origins: [url!], }); await chrome.scripting.executeScript({ target: { tabId: tabId!, allFrames: false }, func: () => console.log('Injected'), world: 'ISOLATED', }); } catch (e) { console.error('Failed to inject script', e); } }); I’ve also hooked into tabs.onActivated, webNavigation.onDOMContentLoaded, and tabs.onCreated events, but nothing seems to trigger the banner. 

 Is there something I’m missing about how Safari handles this? Any advice or pointers would be super helpful. 
 
 
![image](https://github.com/user-attachments/assets/843f37bc-1bb8-4984-ab79-47ddb72b50fc)

**Comment by fregante** [comment]
This kind of questions would be best asked on StackOverflow. 

If you have `<all_urls>` in host_permissions, Safari should automatically show that banner once the browser is opened.

**Comment by wydgetlabsadmin** [comment]
Well the question is if there any way to show the banner again if user has hit don’t allow in the past. Honey and Coupert seem to be able to have this functionality and it is not documented anywhere. There are stackoverflow questions of this nature with no responses.

We have functionality that requires the user to give this all_urls permission, but user sometimes accidentally hit don’t allow, causing a issues for them to be able to change their mind and re-add them

**Comment by carlosjeurissen** [comment]
@wydgetlabsadmin As @fregante mentioned, this is not the place for such questions. There is documentation on permission requests on mdn:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request
