### ISSUE TITLE
New Issue Template

### ISSUE THREAD

**Issue by kewisch** [w3c/webextensions#9]
Hello Folks,

I think we should discuss adding an issue template to help make sure the issues we accumulate here are in scope towards the discussions and the charter. We are mainly aiming to specify the current extensions landscape, and feature requests on top may end up being out of scope. Having an issue template may help reduce issues to triage, and direct participants to other venues where their request would be more helpful (Chrome's crx list, Mozilla's discourse, etc)

Would love to gather your thoughts on this and what we should include.

**Comment by hanguokai** [comment]
At present, as an extension developer, I am not very clear about what should be discussed here. Normally, I report bug or feature request on browser vendor's issue tracker, not here. There will be a template after it is clear what can be discussed here.

**Comment by kewisch** [comment]
Indeed, this is what I'm intending to hash out, determine what should be discussed here. I agree that bug reports and feature requests should continue to occur on the respective browser vendor's bugtrackers.

The "issues" on this repo, should be tasks focused on advancing the [scope of work in the charter](https://github.com/w3c/webextensions/blob/main/charter.md#scope-of-work). I think it will become more clear once there is some structure for the initial work product. When this exists, we'd likely have:
* Identifying a difference in implementation between browser vendors in APIs or contexts common to browsers.
* Filing enhancement issues to track areas that need more documentation or changes

The focus here is initially on the core aspects that browsers have implement today. Since Manifest v3 is not yet finalized nor implemented in all browsers, there will likely be a stronger focus on Manifest v2. That said, I'm guessing the parts of Manifest v2 that are also present in v3 will have some preference.

**Comment by rdcronin** [comment]
Discussed at the WECG meetup.

While we agree there's value in having more of an issue template, we don't think we'll do anything here in the near future.  Our issue tracking and triage has grown organically over the years, and we're reasonably happy with the current process.  We'll continue to iterate (e.g., adding new labels as needed, etc), but we don't think there's much to actively track with this issue.
